function clear(p: player):
    send "&c[Casting] Sequence expired" to {_p}
    delete {casting::sequence::%{_p}%}

function clearlater(p: player):
    wait 5 seconds

    if {casting::sequence::%{_p}%} is set:
        send "&c[Casting] Sequence expired" to {_p}
        delete {casting::sequence::%{_p}%}

function cast(p: player):
    set {_seq} to {casting::sequence::%{_p}%}
    send "&6[Casting] Cast spell: &b%{_seq}%" to {_p}

function add(p: player, t: string):
    set {_seq} to {casting::sequence::%{_p}%}
    set {_seq} to {_seq} + " " + {_t}
    set {casting::sequence::%{_p}%} to {_seq}

    send action bar "&b[Casting] &7%{_seq}%" to {_p}

    if size of {_seq} is 7:
        cast({_p})
        clear({_p})

on right click:
    set {_seq} to {casting::sequence::%player%}

    if {_seq} is not set:
        set {casting::sequence::%player%} to "R"
        send action bar "&b[Casting] &7R" to player
        clearlater(player)

    else if size of {_seq} < 7:
        add(player, "R")

    else:
        cast(player)
        clear(player)

on left click on air:
    set {_seq} to {casting::sequence::%player%}

    if {_seq} is set:
        if size of {_seq} < 7:
            add(player, "L")
        else:
            cast(player)
            clear(player)