on join:
    if player have permission "admin.bypass":
        stop
    teleport player to location(135.5, -51, 22.5, "world", 90, 30)
    set player's gamemode to spectator
    set the player's fly speed to 0
    send title "&c&lʏᴏᴜ ᴡᴇʀᴇ ᴋɪᴅɴᴀᴘᴘᴇᴅ" with subtitle "&cɴᴏᴡ ʏᴏᴜ ᴀʀᴇ ᴏɴ ᴀ &eᴍʏꜱᴛᴇʀɪᴏᴜꜱ ᴛʀᴀɪɴ" to all players for 3 seconds with fade in 5 ticks and fade out 5 ticks
    wait 4 second
    set player's gamemode to adventure
    teleport player to location(-3.5, -54.5, 22.5, "world", -90, 0)