on place of lime concrete:
    cancel event
    if block below event-block is gray stained glass:
        if size of {gen1::%player%::*} >= 20:
            send "&cYou can only have &e20 generators active&7 at once!" to player
            stop
        remove 1 lime concrete from player
        set {_loc} to location of block below event-block
        set block at {_loc} to lime concrete
        add {_loc} to {gen1::%player%::*}
        set data tag "gen1:owner_%x-coord of {_loc}%_%y-coord of {_loc}%_%z-coord of {_loc}%" of chunk at {_loc} to player
    else:
        send "&cYou can only place generators on &egray stained glass&7!" to player
        stop

on right click on lime concrete:
    set {_loc} to location of event-block
    set {_owner} to data tag "gen1:owner_%x-coord of {_loc}%_%y-coord of {_loc}%_%z-coord of {_loc}%" of chunk at {_loc}
    if {_owner} is player:
        cancel event
        set event-block to gray stained glass
        give player 1 lime concrete
        loop {gen1::%player%::*}:
            if loop-value is {_loc}:
                delete {gen1::%player%::%loop-index%}
        delete data tag "gen1:owner_%x-coord of {_loc}%_%y-coord of {_loc}%_%z-coord of {_loc}%" of chunk at {_loc}

function clearPlacements(p: player):
    loop {gen1::%{_p}%::*}:
        set {_loc} to loop-value
        set block at {_loc} to gray stained glass
        delete data tag "gen1:owner_%x-coord of {_loc}%_%y-coord of {_loc}%_%z-coord of {_loc}%" of chunk at {_loc}
    delete {gen1::%{_p}%::*}

command /cleargen:
    trigger:
        clearPlacements(player)
        send "&aAll your hidden generators have been reverted." to player


function makeMoney(money: number) :: item:
    set {_item} to paper named "&6$1"
    set number data tag "money:value" of {_item} to {_money}
    return {_item}

every 1 second in "world":
    loop all players:
        if size of {gen1::%loop-player%::*} > 0:
            loop {gen1::%loop-player%::*}:
                set {_spawnLoc} to location 1 above loop-value
                drop makeMoney(1) at {_spawnLoc} without velocity

function GainMoney(p: player, give: number):
    set {_money} to number data tag "player:money" of {_p}
    if {_money} is not set:
        set {_money} to 0
    set {_temp} to {_money} + {_give}
    set number data tag "player:money" of {_p} to {_temp}

on pickup:
    if event-item is paper:
        set {_value} to number data tag "money:value" of event-item
        if {_value} is set:
            GainMoney(player, {_value})
            delete event-item
            send "&a+$%{_value}%" to player