command /sethome:
    trigger:
        set {_loc::x} to x-coord of player's location
        set {_loc::y} to y-coord of player's location
        set {_loc::z} to z-coord of player's location
        set {_loc::yaw} to yaw of player's location
        set {_loc::pitch} to pitch of player's location
        send "&aYou have sucessfully set a home location."
        set to number list data tag "home:loc" of player to {_loc::*}