function getRarityLine(rarity: text) :: text:
    if {_rarity} is "special":
        return "&cꜱᴘᴇᴄɪᴀʟ"
    if {_rarity} is "divine":
        return "&bᴅɪᴠɪɴᴇ"
    if {_rarity} is "mythic":
        return "&dᴍʏᴛʜɪᴄᴀʟ"
    if {_rarity} is "legendary":
        return "&6ʟᴇɢᴇɴᴅᴀʀʏ"
    if {_rarity} is "epic":
        return "&5ᴇᴘɪᴄ"
    if {_rarity} is "rare":
        return "&9ʀᴀʀᴇ"
    if {_rarity} is "uncommon":
        return "&aᴜɴᴄᴏᴍᴍᴏɴ"
    if {_rarity} is "common":
        return "&fᴄᴏᴍᴍᴏɴ"
    return ""

function material(type: text):: item:
    set {_item} to player head
    
    if {_type} is 1:
        set name of {_item} to "&fWood"
        set {_rarity} to "common"
        set the skull texture of {_item} to "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjU2MGViYzA2OGYyN2M0ZmE4NTIyNTI1MWZkZGQ3NzYyZDA5MTk0MTBlNDVjZDhkMzcyNTM0YzBhYzNiNjFmMSJ9fX0="
    if {_type} is 2:
        set name of {_item} to "&fStone"
        set {_rarity} to "common"
        set the skull texture of {_item} to "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGE5Y2E3MWYwMzFmYzk1YmRmNGE1ZGU1M2RjNDNhNjAzYmU1YjcxZDM2OTJmZDU3M2JmODQxZTA4ZTcyNTAxYyJ9fX0=="
    if {_type} is 3:
        set name of {_item} to "&fRaw Iron"
        set {_rarity} to "uncommon"
        set the skull texture of {_item} to "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODE0MmU3ODgyNzU3ZTBmMzNiZjc0NGI2ZTJhYzdlN2I4NWY1ZjFlNmYyZTJjZDY1NThlZjA4NzNiYTQ2YThmMSJ9fX0="
    if {_type} is 4:
        set name of {_item} to "&f Raw Gold"
        set {_rarity} to "uncommon"
        set the skull texture of {_item} to "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWI2OTk2NzE2M2M3NDNkZGIxZjA4MzU2Njc1NzU3NmI5ZTYzYWMzODBjYzE1MGY1MThiMzNkYzRlOTFlZjcxMiJ9fX0="
    
    set {_rarityLine} to getRarityLine({_rarity})
    
    set line 1 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ɪɴғᴏ"
    set line 2 of lore of {_item} to "&8┃ &7ᴛʏᴘᴇ &8» &eᴍᴀᴛᴇʀɪᴀʟ"
    set line 3 of lore of {_item} to "&8┃ &7ʀᴀʀɪᴛʏ &8» %{_rarityLine}%"
    
    set {_item} to unbreakable {_item}
    set item flags of {_item} to all item flags
    set number data tag "mat:id" of {_item} to {_type}
    
    return {_item}
    
command /givemat <number>:
    permission: admin.item
    trigger:
        set {_item} to material(arg-1)
        give {_item} to player