on join:
    clearPlacements(player)
    teleport player to location(0.5, -59, 0.5, "world")
    set number data tag "player:money" of player to 0
    if number data tag "player:prestige" of player is not set:
        set number data tag "player:pristige" of player to 0
        
on death:
    clearPlacements(victim)
    wait 1 tick
    teleport victim to location(0, -59, 0, "world")
    set number data tag "player:money" of victim to 0
    
command /wipe <player>:
    permission: admin.stat
    trigger:
        set number data tag "player:money" of arg-1 to 0
        set number data tag "player:prestige" of arg-1 to 0
       
function Actionbar(p: player):
    set {_money} to number data tag "player:money" of {_p}
    send action bar "<##00AA00>$%{_money}%" to {_p}
       
every 2 tick in "world":
    loop all players:
        if loop-player is alive:
            Actionbar(loop-player)
            
            
function GainMoney(p: player, give: number):
    set {_money} to number data tag "player:money" of {_p}
    if {_money} is not set:
        set {_money} to 0
    set {_temp} to {_money} + {_give}
    set number data tag "player:money" of {_p} to {_temp}

on pickup:
    if event-item is paper:
        set {_value} to number data tag "money:value" of event-item
        if {_value} is set:
            GainMoney(player, {_value})
            delete event-item
            send "&a+$%{_value}%" to player
    
command /givemoney <number>:
    trigger:
        GainMoney(player, arg-1)
        
on food level change:
    cancel event