on join:
    set {gen1-items::%player%} to 0
    set {gen2-items::%player%} to 0
    clearPlacements(player)
    teleport player to location(0.5, -59, 0.5, "world")
    set number data tag "player:money" of player to 100
    if number data tag "player:prestige" of player is not set:
        set number data tag "player:pristige" of player to 0
        
on death:
    set {gen1-items::%victim%} to 0
    set {gen2-items::%victim%} to 0
    clearPlacements(victim)
    wait 1 tick
    teleport victim to location(0, -59, 0, "world")
    set number data tag "player:money" of victim to 100
    
command /wipe <player>:
    permission: admin.stat
    trigger:
        set number data tag "player:money" of arg-1 to 100
        set number data tag "player:prestige" of arg-1 to 0
       
function Actionbar(p: player):
    set {_money} to number data tag "player:money" of {_p}
    send action bar "<##00AA00>$%{_money}%" to {_p}
       
every 2 tick in "world":
    loop all players:
        if loop-player is alive:
            Actionbar(loop-player)
            
            
function GainMoney(p: player, give: number):
    set {_money} to number data tag "player:money" of {_p}
    if {_money} is not set:
        set {_money} to 0
    set {_temp} to {_money} + {_give}
    set number data tag "player:money" of {_p} to {_temp}

    
command /givemoney <number>:
    trigger:
        GainMoney(player, arg-1)
        
on food level change:
    cancel event