function canPasteNode(loc: location, id: number) :: boolean:
    set {_blocks::*} to {_loc}

    if {_id} > 1:
        set {_l} to {_loc}
        add 1 to x-coordinate of {_l}
        add {_l} to {_blocks::*}

        add 1 to x-coordinate of {_l}
        add {_l} to {_blocks::*}

        add 1 to x-coordinate of {_l}
        add {_l} to {_blocks::*}

        set {_l} to {_loc}
        add 1 to x-coordinate of {_l}
        remove 1 from z-coordinate of {_l}
        add {_l} to {_blocks::*}

        add 1 to x-coordinate of {_l}
        add {_l} to {_blocks::*}

        set {_l} to {_loc}
        add 1 to x-coordinate of {_l}
        add 1 to z-coordinate of {_l}
        add {_l} to {_blocks::*}

        add 1 to x-coordinate of {_l}
        add {_l} to {_blocks::*}

        set {_l} to {_loc}
        add 1 to x-coordinate of {_l}
        add 1 to y-coordinate of {_l}
        add {_l} to {_blocks::*}

        add 1 to x-coordinate of {_l}
        add {_l} to {_blocks::*}
    else:
        set {_l} to {_loc}
        loop 2 times:
            add 1 to x-coordinate of {_l}
            add {_l} to {_blocks::*}

    loop {_blocks::*}:
        if block at loop-value is not air:
            return false

    return true

function pasteNode1(loc: location):
    loop 3 times:
        set block data of block at {_loc} to oak_log[axis=x]
        add 1 to x-coordinate of {_loc}
        
function pasteNode2(loc: location):
    set {_l} to {_loc}
    set block at {_l} to cobblestone
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    remove 1 from z-coordinate of {_l}
    set block at {_l} to stone
    add 1 to x-coordinate of {_l}
    set block at {_l} to cobblestone_slab[type=bottom]

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    add 1 to z-coordinate of {_l}
    set block at {_l} to stone
    add 1 to x-coordinate of {_l}
    set block at {_l} to cobblestone

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    add 1 to y-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]
    
function pasteNode3(loc: location):
    set {_l} to {_loc}
    set block at {_l} to cobblestone
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone
    add 1 to x-coordinate of {_l}
    set block at {_l} to iron ore
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    remove 1 from z-coordinate of {_l}
    set block at {_l} to iron ore
    add 1 to x-coordinate of {_l}
    set block at {_l} to cobblestone_slab[type=bottom]

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    add 1 to z-coordinate of {_l}
    set block at {_l} to iron ore
    add 1 to x-coordinate of {_l}
    set block at {_l} to cobblestone

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    add 1 to y-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]
    
function pasteNode4(loc: location):
    set {_l} to {_loc}
    set block at {_l} to cobblestone
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone
    add 1 to x-coordinate of {_l}
    set block at {_l} to gold ore
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    remove 1 from z-coordinate of {_l}
    set block at {_l} to gold ore
    add 1 to x-coordinate of {_l}
    set block at {_l} to cobblestone_slab[type=bottom]

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    add 1 to z-coordinate of {_l}
    set block at {_l} to gold ore
    add 1 to x-coordinate of {_l}
    set block at {_l} to cobblestone

    set {_l} to {_loc}
    add 1 to x-coordinate of {_l}
    add 1 to y-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]
    add 1 to x-coordinate of {_l}
    set block at {_l} to stone_slab[type=bottom]
        
function PasteNode(loc: location, id: number):
    if canPasteNode({_loc}, {_id}) is false:
        stop

    switch {_id}:
        case 1:
            pasteNode1({_loc})
        case 2:
            pasteNode2({_loc})
        case 3:
            pasteNode3({_loc})
        case 4:
            pasteNode4({_loc})
        
command /nodepaste <number>:
    permission: admin.node
    trigger:
        set {_loc} to player's location
        add 1 to x-coord of {_loc}
        PasteNode({_loc}, arg-1)
