function openRules(p: audience):
    open multi action dialog to {_p}:
        title: "&aꜱᴇʀᴠᴇʀ ʀᴜʟᴇꜱ"
        can_close_with_escape: false
        columns: 1
        body:
            add plain message body:
                contents: "&a&lᴘʟᴇᴀꜱᴇ ʀᴇᴀᴅ ᴏᴜʀ ꜱᴇʀᴠᴇʀ ʀᴜʟᴇꜱ!"
            add plain message body:
                contents: "&8&m-------------------------"
            add plain message body:
                contents: "&a&l#1 &8» &fɴᴏ ᴜɴꜰᴀɪʀ ᴀᴅᴠᴀɴᴛᴀɢᴇ."
            add plain message body:
                contents: "&a&l#2 &8» &fɴᴏ ᴅᴜᴘʟɪᴄᴀᴛɪᴏɴ ɢʟɪᴛᴄʜᴇs."
            add plain message body:
                contents: "&a&l#3 &8» &fɴᴏ ᴅᴏxxɪɴɢ ᴏʀ ʀʟ ᴛʜʀᴇᴀᴛs."
            add plain message body:
                contents: "&a&l#4 &8» &fɴᴏ sᴘᴀᴡɴ ᴄᴀᴍᴘɪɴɢ."
            add plain message body:
                contents: "&8&m-------------------------"
        actions:
            add callback action button:
                label: "Accept"
                trigger:
                    unfreeze connection event-playerconnection
            add callback action button:
                label: "Decline"
                trigger:
                    unfreeze connection event-playerconnection and disconnect due to "&cOk fine... bye!"

command /test:
    trigger:
        openRules(player)