command /saveitem <text>:
    permission: admin.save
    trigger:
        if player's tool is air:
            send "&cYou're not holding anything!" to player
            stop
        set {item::%arg-1%} to player's tool
        send "&aSaved item as &e%arg-1%" to player

command /giveitem <text>:
    permission: admin.save
    trigger:
        if {item::%arg-1%} is set:
            give {item::%arg-1%} to player
            send "&aGave you item &e%arg-1%" to player
        else:
            send "&cNo item found with id &e%arg-1%" to player
            
command /pdcset [<text>] [<text>]:
    permission: admin.create
    trigger:
        set {_item} to player's held item
        set {_key} to arg-1
        set {_val} to arg-2
        set data tag {_key} of {_item} to {_val}
        set player's held item to {_item}
        send "&aSet &e%{_key}% &a= &e%{_val}%&a on held item."

function openOre(p: player):
    set {_gui} to chest inventory with 4 rows named "<##E9BF35>ꜰᴏʀɢɪɴɢ ɢᴜɪ"

    loop 36 times:
        set slot (loop-number - 1) of {_gui} to {item::space}
        
    open {_gui} to {_p}
    
on inventory click:
    name of event-inventory is "<##E9BF35>ꜰᴏʀɢɪɴɢ ɢᴜɪ"
    set {_temp} to data tag "item:id" of event-item
    if {_temp} is "1":
        cancel event
        stop
    
command /test:
    trigger:
        openOre(player)