command /spawn [<player>]:
    description: Teleports you or another player to spawn
    trigger:
        if arg-1 is set:
            if player does not have permission "admin.spawn":
                send "&c✖ &8| &cYou do not have permission to teleport others!" to player
                stop
            teleport arg-1 to location(-699.5, 69, 822.5, world "world", 180, 0)
            play sound "entity.enderman.teleport" at arg-1 for arg-1
            send title "&a✔ &aTeleported to spawn!" with subtitle "&7By administrator!" to player for 1.6 seconds
            send "&a✔ &8| &aTeleported &e%arg-1% &ato spawn!" to player
            stop
        teleport player to location(-699.5, 69, 822.5, world "world", 180, 0)
        play sound "entity.enderman.teleport" at player for player
        send title "&a✔ &aTeleported to spawn!" to player for 1.6 seconds

on respawn:
    wait 20 ticks
    teleport player to location(-699.5, 69, 822.5, world "world", 180, 0)
    send title "&a✔ &aTeleported to spawn!" with subtitle "&4You have died!" to player for 1.6 seconds

on first join:
    wait 1 tick
    teleport player to location(-701.5, 54, 821.5, world "world", 180, 0)