on join:
    set number data tag "money:amm" of player to 100
    
command /bal [<player>]:
    trigger:
        if arg-1 is set:
            if player has permission "admin.bal":
                set {_bal} to number data tag "money:amm" of arg-1
                set {_p} to SmallCaps("%arg-1%")
                send "&8[<##65b9d3>ᴍᴏɴᴇʏ&8]&e %{_p}%'s &7ᴄᴜʀʀᴇɴᴛ ʙᴀʟᴀɴᴄᴇ ɪꜱ &e%{_bal}%&7."
                stop
        set {_bal} to number data tag "money:amm" of player
        send "&8[<##65b9d3>ᴍᴏɴᴇʏ&8]&7 ʏᴏᴜʀ ᴄᴜʀʀᴇɴᴛ ʙᴀʟᴀɴᴄᴇ ɪꜱ &e%{_bal}%&7."
        
command /pay [<player>] [<number>]:
    trigger:
        if arg-1 is not set:
            send "&8[<##65b9d3>ᴍᴏɴᴇʏ&8]&c /ᴘᴀʏ <ᴘʟᴀʏᴇʀ> <ᴍᴏɴᴇʏ>"
        if arg-1 is offline:
            send "&8[<##65b9d3>ᴍᴏɴᴇʏ&8]&c ʏᴏᴜ ᴄᴀɴ'ᴛ ꜱᴇɴᴅ ᴍᴏɴᴇʏ ᴛᴏ ᴏꜰꜰʟɪɴᴇ ᴘʟᴀʏᴇʀꜱ."
            stop
        if arg-2 <= 0:
            send "&8[<##65b9d3>ᴍᴏɴᴇʏ&8]&c ʏᴏᴜ ᴄᴀɴ'ᴛ ꜱᴇɴᴅ ᴍᴏɴᴇʏ ᴇǫᴜᴀʟ ᴏʀ ʟᴇꜱꜱ ᴛʜᴇɴ ᴢᴇʀᴏ."
            stop
        send "work"