function StartFloor(room: number, floor: number):
    if {_floor} = 1:
        floor1({_room})
    if {_floor} = 2:
        floor2({_room})
    if {_floor} = 3:
        floor3({_room})
    if {_floor} = 4:
        floor4({_room})
    if {_floor} = 5:
        floor5({_room})
    if {_floor} = 6:
        floor6({_room})
    if {_floor} = 7:
        floor7({_room})
    if {_floor} = 8:
        floor8({_room})
        
function floor1(room: number):
    spawnMob(8, {_room}, 1, "undead1", 1)