function craftgui(p: player):
    set {_gui} to chest inventory with 3 rows named "<##E9BF35>ꜰᴏʀɢɪɴɢ ɢᴜɪ"

    loop 27 times:
        set slot (loop-number - 1) of {_gui} to {item::space}
        
    set slot 10 of {_gui} to air
    set slot 12 of {_gui} to air
    set slot 16 of {_gui} to air

    open {_gui} to {_p}
    
on inventory click:
    name of event-inventory is "<##E9BF35>ꜰᴏʀɢɪɴɢ ɢᴜɪ"
    set {_temp} to data tag "item:id" of event-item
    if {_temp} is "1":
        cancel event

    
command /test1:
    trigger:
        craftgui(player)